name: ChestRefiller
version: 1.0.0
api-version: 1.19
author: Hakuyamu
main: de.skycave.chestrefiller.ChestRefiller
depend:
  - SkyBeeCore

commands:
  chestrefill:
    aliases: [crefill]
    permission: skycave.chestrefiller.chestrefill